"use client"
import './globals.css'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import { useRouter } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  const router = useRouter()
  const onClickURL = (url) => {
    router.push(url)
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <ul className="flex gap-3 mt-5 ml-3 mb-5">
          <li className="bg-sky-600 py-1 px-2 rounded-lg shadow-lg hover:scale-105 duration-500 text-white font-bold hover:bg-gradient-to-t from-sky-600 to-sky-400">
            <Link href="/">Home</Link>
          </li>
          <li className="bg-sky-600 py-1 px-2 rounded-lg shadow-lg hover:scale-105 duration-500 text-white font-bold hover:ring-slate-800 hover:bg-gradient-to-t from-sky-600 to-sky-400">
            <Link href="/dashboard">Dashboard</Link>
          </li>
          <li
            className="bg-sky-600 py-1 px-2 rounded-lg cursor-pointer shadow-lg hover:scale-105 duration-500 text-white font-bold hover:ring-slate-800 hover:bg-gradient-to-t from-sky-600 to-sky-400"
            onClick={() => onClickURL("/settings")}
          >
            Settings
          </li>
        </ul>
        {children}
        {/* <div>Footer</div> */}
      </body>
    </html>
  );
}
