// import './globals.css'
"use client"
import { Inter } from 'next/font/google'
import Link from 'next/link'
import { useRouter } from 'next/navigation'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  const router = useRouter()
  const onClickURL = (url) => {
    router.push(url)
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <ul>
          <li>
            <Link href="/">Home</Link>
          </li>
          <li>
            <Link href="/dashboard">Dashboard</Link>
          </li>
          <li style={{backgroundColor: 'black',color: 'white', width: '60px', textAlign: 'center', cursor: 'pointer',padding: '5px', border: 'none', borderRadius: '6px'}} onClick={() => onClickURL('/settings')}>Settings</li>
        </ul>
        {children}
        <div>Footer</div>
      </body>
    </html>
  );
}
